[[pages]]
path = "my_pages/home.py"
name = "Home"
icon = ":material/home:"

[[pages]]
path = "my_pages/file_upload.py"
name = "File upload"
icon = ":material/upload:"

[[pages]]
path = "my_pages/params.py"
name = "Parameters"
icon = ":material/tune:"

[[pages]]
path = "my_pages/dashboard.py"
name = "Statistics & Visualizations"
icon = ":material/finance:"